"""
Tests for serialization of GPSTime objects within other structures.

Includes code generated by Gemini 2.0
"""
from __future__ import annotations
from io import StringIO
import datetime
import pytest
import ruamel.yaml
from gps_time import GPSTime

class SatelliteSnapshot:
    """A container class for testing purposes."""
    
    yaml_tag = u"!SatelliteSnapshot"

    def __init__(self, satellite_id: int, time: GPSTime, velocity: float) -> None:
        self.satellite_id = satellite_id
        self.time = time
        self.velocity = velocity

    def __repr__(self) -> str:
        return f"SatelliteSnapshot(id={self.satellite_id}, time={self.time}, vel={self.velocity})"
    
    def __eq__(self, other: object) -> bool:
        if not isinstance(other, SatelliteSnapshot):
            return NotImplemented
        return (self.satellite_id == other.satellite_id and 
                self.time == other.time and 
                self.velocity == other.velocity)

@pytest.fixture
def yaml():
    """Fixture to provide a configured YAML instance."""
    y = ruamel.yaml.YAML()
    y.register_class(GPSTime)
    y.register_class(SatelliteSnapshot)
    return y

def test_nested_gpstime_serialization(yaml):
    """Test serializing a custom object that contains a GPSTime."""
    original_snapshot = SatelliteSnapshot(
        satellite_id=12,
        time=GPSTime(week_number=2290, seconds=123456, femtoseconds=0),
        velocity=3100.5
    )

    stream = StringIO()
    yaml.dump(original_snapshot, stream)
    yaml_string = stream.getvalue()

    stream = StringIO(yaml_string)
    loaded_snapshot = yaml.load(stream)

    assert loaded_snapshot == original_snapshot

def test_direct_gpstime_serialization(yaml):
    """Test serializing a GPSTime object directly."""
    original_time = GPSTime(week_number=2290, seconds=123456, femtoseconds=0)
    
    stream = StringIO()
    yaml.dump(original_time, stream)
    yaml_string = stream.getvalue()

    # Basic check to ensure it looks reasonable
    assert "!GPSTime" in yaml_string
    
    stream = StringIO(yaml_string)
    loaded_time = yaml.load(stream)

    assert loaded_time == original_time
    assert loaded_time.week_number == 2290
    assert loaded_time.seconds == 123456

@pytest.mark.parametrize("gpstime_instance", [
    GPSTime.from_datetime(datetime.datetime(2023, 11, 23, 12, 0, 0)),
    GPSTime(week_number=2290, time_of_week=123456.789),
    GPSTime(week_number=1000, seconds=0, femtoseconds=0),
    GPSTime(week_number=2048, seconds=604799, femtoseconds=999999999999999), 
])
def test_gpstime_variations(yaml, gpstime_instance):
    """Test various ways of constructing GPSTime are preserved after round-trip."""
    stream = StringIO()
    yaml.dump(gpstime_instance, stream)
    yaml_string = stream.getvalue()
    
    stream = StringIO(yaml_string)
    loaded_time = yaml.load(stream)

    assert loaded_time == gpstime_instance
    # Ensure precision is maintained
    if gpstime_instance.femtoseconds > 0:
        assert loaded_time.femtoseconds == gpstime_instance.femtoseconds
    if gpstime_instance.seconds > 0:
        assert loaded_time.seconds == gpstime_instance.seconds

